### ISSUE TITLE
Unable to log in to dashboard

### ISSUE THREAD

**Issue by troykelly** [hassio-addons/addon-shinobi#10]
# Problem/Motivation

Unable to install and use shinobi addon

## Expected behaviour

Addon installs and the dashboard is accessible via the web ui

## Actual behaviour

Addon installs.
On starting - addon generates errors - https://pastebin.com/S9MhHkWy
Once started:
Unable to log in with username/password configured. Login page just refreshes.

## Steps to reproduce

Add shinobi addon. Click start. Open WebUI. Login with default credentials.

## Proposed changes

None at this time.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/S9MhHkWy">Shinobi Startup Issues - Pastebin.com</a></strong></div></blockquote>

**Comment by jaclindberg** [comment]
This is because you didn't read the documentation correctly. 

https://github.com/hassio-addons/addon-shinobi/blob/v0.2.0/README.md

The installation of this add-on is pretty straightforward and not different in comparison to installing any other Hass.io add-on.

Add our Hass.io add-ons repository to your Hass.io instance.
Install the "Shinobi Pro" add-on.
Start the "Shinobi Pro" add-on
Check the logs of the "Shinobi Pro" add-on to see if everything went well.
Surf to the superuser admin panel: http://hassio.local:7440/super
Log in with the superuser credentials as specified in the add-on configuration.
Create a Shinobi user account.
Logout from the superuser panel.
You are now ready to use Shinobi, use the freshly created login from now on.

**Comment by frenck** [comment]
This add-on has been deprecated some time ago already and has now been removed from the add-on store.

If you are looking for an alternative: https://github.com/hassio-addons/addon-motioneye

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-motioneye">hassio-addons/addon-motioneye</a></strong></div><div>motionEye - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-motioneye</div></blockquote>
